"""Initial migration

Revision ID: 04e644f5403b
Revises: 
Create Date: 2025-02-15 19:58:58.050895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e644f5403b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('continent',
    sa.Column('id_continent', sa.Integer(), nullable=False),
    sa.Column('code_continent', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_continent'),
    sa.UniqueConstraint('code_continent')
    )
    op.create_table('maladie',
    sa.Column('code_maladie', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('code_maladie'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('periode',
    sa.Column('code_periode', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('code_periode'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('pays',
    sa.Column('id_pays', sa.String(), nullable=False),
    sa.Column('code_pays', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('pib', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('code_continent', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['code_continent'], ['continent.code_continent'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pays'),
    sa.UniqueConstraint('code_pays')
    )
    op.create_table('rapport',
    sa.Column('code_rapport', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('nouveaux_cas', sa.Integer(), nullable=True),
    sa.Column('nouveaux_deces', sa.Integer(), nullable=True),
    sa.Column('nouveaux_gueris', sa.Integer(), nullable=True),
    sa.Column('cas_actifs', sa.Integer(), nullable=True),
    sa.Column('taux_mortalite', sa.Integer(), nullable=True),
    sa.Column('taux_guerison', sa.Integer(), nullable=True),
    sa.Column('code_maladie', sa.Integer(), nullable=False),
    sa.Column('code_periode', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['code_maladie'], ['maladie.code_maladie'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['code_periode'], ['periode.code_periode'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code_rapport')
    )
    op.create_table('region',
    sa.Column('id_region', sa.Integer(), nullable=False),
    sa.Column('code_region', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('code_pays', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['code_pays'], ['pays.code_pays'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_region'),
    sa.UniqueConstraint('code_region')
    )
    op.create_table('concerne',
    sa.Column('code_continent', sa.String(), nullable=False),
    sa.Column('code_pays', sa.String(), nullable=False),
    sa.Column('code_region', sa.String(), nullable=False),
    sa.Column('code_rapport', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['code_continent'], ['continent.code_continent'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['code_pays'], ['pays.code_pays'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['code_rapport'], ['rapport.code_rapport'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['code_region'], ['region.code_region'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code_continent', 'code_pays', 'code_region', 'code_rapport')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concerne')
    op.drop_table('region')
    op.drop_table('rapport')
    op.drop_table('pays')
    op.drop_table('periode')
    op.drop_table('maladie')
    op.drop_table('continent')
    # ### end Alembic commands ###
