"""Initial migration

Revision ID: 094451e1765b
Revises: 
Create Date: 2025-02-01 04:10:56.493622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094451e1765b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('continent',
    sa.Column('code_continent', sa.String(length=10), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('code_continent')
    )
    op.create_table('maladie',
    sa.Column('id_maladie', sa.String(length=10), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('total_cas', sa.Integer(), nullable=True),
    sa.Column('total_deces', sa.Integer(), nullable=True),
    sa.Column('total_gueris', sa.Integer(), nullable=True),
    sa.Column('total_tests', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_maladie')
    )
    op.create_table('pays',
    sa.Column('code_pays', sa.String(length=10), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('nom_continent', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('code_pays')
    )
    op.create_table('region',
    sa.Column('code_region', sa.String(length=10), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('nom_pays', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('code_region')
    )
    op.create_table('statistiques_globales',
    sa.Column('code_stats', sa.String(length=10), nullable=False),
    sa.Column('total_cas', sa.Integer(), nullable=True),
    sa.Column('total_deces', sa.Integer(), nullable=True),
    sa.Column('total_gueris', sa.Integer(), nullable=True),
    sa.Column('total_tests', sa.Integer(), nullable=True),
    sa.Column('date_maj', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('code_stats')
    )
    op.create_table('cumule',
    sa.Column('id_maladie', sa.String(length=10), nullable=False),
    sa.Column('code_stats', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['code_stats'], ['statistiques_globales.code_stats'], ),
    sa.ForeignKeyConstraint(['id_maladie'], ['maladie.id_maladie'], ),
    sa.PrimaryKeyConstraint('id_maladie', 'code_stats')
    )
    op.create_table('rapport_quotidien',
    sa.Column('id_rapport', sa.String(length=10), nullable=False),
    sa.Column('date_rapport', sa.Date(), nullable=True),
    sa.Column('nouveaux_cas', sa.Integer(), nullable=True),
    sa.Column('nouveaux_deces', sa.Integer(), nullable=True),
    sa.Column('nouveaux_gueris', sa.Integer(), nullable=True),
    sa.Column('cas_actifs', sa.Integer(), nullable=True),
    sa.Column('taux_mortalite', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('taux_guerison', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('id_maladie', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['id_maladie'], ['maladie.id_maladie'], ),
    sa.PrimaryKeyConstraint('id_rapport')
    )
    op.create_table('concerne',
    sa.Column('id_rapport', sa.String(length=10), nullable=False),
    sa.Column('code_continent', sa.String(length=10), nullable=False),
    sa.Column('code_pays', sa.String(length=10), nullable=True),
    sa.Column('code_region', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['code_continent'], ['continent.code_continent'], ),
    sa.ForeignKeyConstraint(['code_pays'], ['pays.code_pays'], ),
    sa.ForeignKeyConstraint(['code_region'], ['region.code_region'], ),
    sa.ForeignKeyConstraint(['id_rapport'], ['rapport_quotidien.id_rapport'], ),
    sa.PrimaryKeyConstraint('id_rapport', 'code_continent')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concerne')
    op.drop_table('rapport_quotidien')
    op.drop_table('cumule')
    op.drop_table('statistiques_globales')
    op.drop_table('region')
    op.drop_table('pays')
    op.drop_table('maladie')
    op.drop_table('continent')
    # ### end Alembic commands ###
