"""Initial migration

Revision ID: 282de599e4c4
Revises: 
Create Date: 2025-02-16 19:46:53.470305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282de599e4c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('continent',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('code_continent', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_continent')
    )
    op.create_table('maladie',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('periode',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('pays',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('code_pays', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('pib', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('code_continent', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['code_continent'], ['continent.code_continent'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_pays')
    )
    op.create_table('rapport',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('nouveaux_cas', sa.Integer(), nullable=True),
    sa.Column('nouveaux_deces', sa.Integer(), nullable=True),
    sa.Column('nouveaux_gueris', sa.Integer(), nullable=True),
    sa.Column('cas_actifs', sa.Integer(), nullable=True),
    sa.Column('taux_mortalite', sa.Integer(), nullable=True),
    sa.Column('taux_guerison', sa.Integer(), nullable=True),
    sa.Column('code_maladie', sa.Integer(), nullable=False),
    sa.Column('code_periode', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['code_maladie'], ['maladie.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['code_periode'], ['periode.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('code_region', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('code_pays', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['code_pays'], ['pays.code_pays'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_region')
    )
    op.create_table('concerne',
    sa.Column('code_continent', sa.String(), nullable=False),
    sa.Column('code_pays', sa.String(), nullable=False),
    sa.Column('code_region', sa.String(), nullable=False),
    sa.Column('code_rapport', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['code_continent'], ['continent.code_continent'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['code_pays'], ['pays.code_pays'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['code_rapport'], ['rapport.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['code_region'], ['region.code_region'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code_continent', 'code_pays', 'code_region', 'code_rapport')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concerne')
    op.drop_table('region')
    op.drop_table('rapport')
    op.drop_table('pays')
    op.drop_table('periode')
    op.drop_table('maladie')
    op.drop_table('continent')
    # ### end Alembic commands ###
